### ISSUE TITLE
stuck on bot is thinking

### ISSUE THREAD

**Issue by 8FrMc** [newQuery/discord-vouch-bot#1]
lmfao

**Comment by newQuery** [comment]
Does your bot has permission to write ?

**Comment by Anotherone123qwerty** [comment]
having the same issue I gave the bot admin and all of its perms and needs and yet it still doesn't work and just gives me on still thinking and is stuck on that forever

**Comment by Anotherone123qwerty** [comment]
But it also says "you can only use this command in #vouches channel" when I run /restore. So where in the src can I change the vouch channel?

**Comment by newQuery** [comment]
Hi, thanks for notifying this to me. I will look into it tomorrow and update the Readme as it needs.
IMO there are something in addition to be done during the installation as I implemented the /restore cmd recently

**Comment by newQuery** [comment]
The issue was either because your server was not aware of the correct context of the command, to fix that simply kick and reinvite your bot.
Make sure that is has permission set correctly (See README)

Or it could have been because you had no ` database.db ` created. Which is now generated on the fly if the file does not exists.
